config/routes.rb
Rails.application.routes.draw do
  resources :material_sheets do 
      get :autocomplete_material_nombre, :on => :collection
  end
  resources :sheets
  resources :materials

end

app/models/material.rb
class Material < ActiveRecord::Base
	has_many :material_sheets

	 # metodos autocomplete
	  def material_nombre
	      material.nombre if material
	  end

	  def material_nombre=(nombre)
	      self.material = Material.find_by_nombre(nombre)
	  end

end

app/models/material_sheet.rb
class MaterialSheet < ActiveRecord::Base
  belongs_to :sheet
  belongs_to :material_sheet

  after_create :validar

  def validar
  	c = Material.where(nombre: self.material_id)
  	if c.count == 0
  		Material.create(nombre: self.material_id)
  	end
  end
end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
	has_many :material_sheets

	accepts_nested_attributes_for :material_sheets, reject_if: :all_blank, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/material_sheets_controller.rb
class MaterialSheetsController < ApplicationController
  before_action :set_material_sheet, only: [:show, :edit, :update, :destroy]

  autocomplete :material, :nombre, full: false
  # GET /material_sheets
  # GET /material_sheets.json
  def index
    @material_sheets = MaterialSheet.all
  end

  # GET /material_sheets/1
  # GET /material_sheets/1.json
  def show
  end

  # GET /material_sheets/new
  def new
    @material_sheet = MaterialSheet.new
  end

  # GET /material_sheets/1/edit
  def edit
  end

  # POST /material_sheets
  # POST /material_sheets.json
  def create
    @material_sheet = MaterialSheet.new(material_sheet_params)

    respond_to do |format|
      if @material_sheet.save
        format.html { redirect_to @material_sheet, notice: 'Material sheet was successfully created.' }
        format.json { render :show, status: :created, location: @material_sheet }
      else
        format.html { render :new }
        format.json { render json: @material_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /material_sheets/1
  # PATCH/PUT /material_sheets/1.json
  def update
    respond_to do |format|
      if @material_sheet.update(material_sheet_params)
        format.html { redirect_to @material_sheet, notice: 'Material sheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @material_sheet }
      else
        format.html { render :edit }
        format.json { render json: @material_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /material_sheets/1
  # DELETE /material_sheets/1.json
  def destroy
    @material_sheet.destroy
    respond_to do |format|
      format.html { redirect_to material_sheets_url, notice: 'Material sheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material_sheet
      @material_sheet = MaterialSheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_sheet_params
      params.require(:material_sheet).permit(:material_id, :cantidad, :sheet_id)
    end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:nombre)
    end
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_action :set_sheet, only: [:show, :edit, :update, :destroy]

  # GET /sheets
  # GET /sheets.json
  def index
    @sheets = Sheet.all
  end

  # GET /sheets/1
  # GET /sheets/1.json
  def show
  end

  # GET /sheets/new
  def new
    @sheet = Sheet.new
  end

  # GET /sheets/1/edit
  def edit
  end

  # POST /sheets
  # POST /sheets.json
  def create
    @sheet = Sheet.new(sheet_params)

    respond_to do |format|
      if @sheet.save
        format.html { redirect_to @sheet, notice: 'Sheet was successfully created.' }
        format.json { render :show, status: :created, location: @sheet }
      else
        format.html { render :new }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sheets/1
  # PATCH/PUT /sheets/1.json
  def update
    respond_to do |format|
      if @sheet.update(sheet_params)
        format.html { redirect_to @sheet, notice: 'Sheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @sheet }
      else
        format.html { render :edit }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sheets/1
  # DELETE /sheets/1.json
  def destroy
    @sheet.destroy
    respond_to do |format|
      format.html { redirect_to sheets_url, notice: 'Sheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sheet
      @sheet = Sheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sheet_params
      params.require(:sheet).permit(:nombre, :descripcion, material_sheets_attributes: [:id, :material_id, :cantidad, :sheet_id, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/material_sheets_helper.rb
module MaterialSheetsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cocoon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/material_sheets/_form.html.erb
<%= form_for(@material_sheet) do |f| %>
  <% if @material_sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material_sheet.errors.count, "error") %> prohibited this material_sheet from being saved:</h2>

      <ul>
      <% @material_sheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :material_id %><br>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :sheet_id %><br>
    <%= f.text_field :sheet_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/material_sheets/edit.html.erb
<h1>Editing Material Sheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @material_sheet %> |
<%= link_to 'Back', material_sheets_path %>

app/views/material_sheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Material Sheets</h1>

<table>
  <thead>
    <tr>
      <th>Material</th>
      <th>Cantidad</th>
      <th>Sheet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @material_sheets.each do |material_sheet| %>
      <tr>
        <td><%= material_sheet.material_id %></td>
        <td><%= material_sheet.cantidad %></td>
        <td><%= material_sheet.sheet %></td>
        <td><%= link_to 'Show', material_sheet %></td>
        <td><%= link_to 'Edit', edit_material_sheet_path(material_sheet) %></td>
        <td><%= link_to 'Destroy', material_sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material sheet', new_material_sheet_path %>

app/views/material_sheets/new.html.erb
<h1>New Material Sheet</h1>

<%= render 'form' %>

<%= link_to 'Back', material_sheets_path %>

app/views/material_sheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Material:</strong>
  <%= @material_sheet.material_id %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @material_sheet.cantidad %>
</p>

<p>
  <strong>Sheet:</strong>
  <%= @material_sheet.sheet %>
</p>

<%= link_to 'Edit', edit_material_sheet_path(@material_sheet) %> |
<%= link_to 'Back', material_sheets_path %>

app/views/materials/_form.html.erb
<%= form_for(@material) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing Material</h1>

<%= render 'form' %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Materials</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.nombre %></td>
        <td><%= link_to 'Show', material %></td>
        <td><%= link_to 'Edit', edit_material_path(material) %></td>
        <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material', new_material_path %>

app/views/materials/new.html.erb
<h1>New Material</h1>

<%= render 'form' %>

<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @material.nombre %>
</p>

<%= link_to 'Edit', edit_material_path(@material) %> |
<%= link_to 'Back', materials_path %>

app/views/sheets/_form.html.erb
<%= form_for(@sheet) do |f| %>
  <% if @sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sheet.errors.count, "error") %> prohibited this sheet from being saved:</h2>

      <ul>
      <% @sheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <h1 class="center">Muestra</h1>

  <div class="fielset">
    <%= f.fields_for :material_sheets do |material_sheet| %>
        <%= render 'material_sheet_fields', f: material_sheet %>
    <% end %>
    <%= link_to_add_association 'Agregar', f, :material_sheets, {data: {'association-insertion-method' => 'after'}} %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sheets/_material_sheet_fields.html.erb
<div class="nested-fields well">
	<div class="field">
		<%= f.label :material_id, 'Material' %><br>
		<%=f.autocomplete_field :material_id, autocomplete_material_nombre_material_sheets_path, :placeholder => "Nombre..." %>
	</div>
	<div class="field">
		<%= f.label :cantidad %><br>
		<%= f.text_field :cantidad %>
	</div>
	<%= link_to_remove_association 'Eliminar', f %>
</div>

app/views/sheets/edit.html.erb
<h1>Editing Sheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @sheet %> |
<%= link_to 'Back', sheets_path %>

app/views/sheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sheets</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sheets.each do |sheet| %>
      <tr>
        <td><%= sheet.nombre %></td>
        <td><%= sheet.descripcion %></td>
        <td><%= link_to 'Show', sheet %></td>
        <td><%= link_to 'Edit', edit_sheet_path(sheet) %></td>
        <td><%= link_to 'Destroy', sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sheet', new_sheet_path %>

app/views/sheets/new.html.erb
<h1>New Sheet</h1>

<%= render 'form' %>

<%= link_to 'Back', sheets_path %>

app/views/sheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @sheet.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @sheet.descripcion %>
</p>

<table>
	<thead>
		<tr>
			<th>Material</th>
			<th>Cantidád</th>
		</tr>
	</thead>
	<tbody>
	<% @sheet.material_sheets.each do |material_sheet| %>
		<tr>
			<td><%= material_sheet.material_id rescue nil %></td>
			<td><%= material_sheet.cantidad %></td>
		</tr>
	<% end %>	
	</tbody>
</table>

	
	


<%= link_to 'Edit', edit_sheet_path(@sheet) %> |
<%= link_to 'Back', sheets_path %>